# Get editor completions based on the config schema
'' = 'https://starship.rs/config-schema.json'

# Disables the custom module: https://docs.warp.dev/features/prompt#starship
[custom]
disabled = false

add_newline = true
[character]
format = "[\\$](green bold) "

[directory]
truncation_length = 3

[git_branch]
symbol = ''
format = '\([$symbol$branch(:$remote_branch)]($style)\)'

[git_status]
format = '([$all_status$ahead_behind]($style) )'
conflicted = ''
ahead = ''
behind = ''
diverged = ''
up_to_date = 'âœ“'
untracked = ''
stashed = ''
modified = 'ðŸ”¥'
staged = ''
renamed = ''
deleted = ''

[package]
disabled = true
